name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: bullseye
    steps:
    - uses: actions/checkout@v3
    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apt-get install make jupyter-nbconvert gawk inkscape latexmk biber
          make    
      
    - name: Run clean
      run: make clean
