name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: bullseye
    steps:
    - uses: actions/checkout@v3
      with:
        run: |
          apt-get update -q -y
          apt-get install make jupyter-nbconvert gawk inkscape latexmk biber texlive texlive-lang-korean texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra texlive-science
          make
